### ISSUE TITLE
Meta/docs: Add quick start pages for other cloud installers

### ISSUE THREAD

**Issue by vdice** [fermyon/installer#89]
https://fermyon.dev is the docs site for this repo and the Fermyon platform.  Currently, it has pages for the local and AWS installer scenarios.

As of writing, this repo now has installers for [GCP](https://github.com/fermyon/installer/tree/main/gcp) and [DigitalOcean](https://github.com/fermyon/installer/tree/main/digitalocean), with [Azure](https://github.com/fermyon/installer/pull/81) in the wings.  It would be great to have a page for each.

For a pattern to follow, see the [AWS Quick Start doc](https://github.com/fermyon/installer/blob/main/docs/content/quickstart-aws.md).

- [ ] GCP Quick Start doc
- [ ] DigitalOcean Quick Start doc
- [ ] Azure Quick Start doc
